---
# page-size can be one of A5, A4, A3, Letter or Legal
# If you choose A5, A4, A3, then all metrics are in mm
# If you choose Letter or Legal, then all metrics are in inches
page-size: A5

# For the PDF meta-data
pdf-title: 2023 Recurring Journal
pdf-author: Lou Franco

# The defaults are used on each page that doesn't override them
defaults:

  # Default year for the journal (can override at page level)
  year: 2023

  # To format dates in titles
  date-format: "%-d %b"

  # The base design of the paper
  paper:
    # type can be blank, dot, or grid.
    type: dot
    # Used to draw the dot, which is a filled ellipse
    # Grid would use the same variables for lines
    spacing: 5
    dot-size: 0.5
    color: "#aaa"

  # When drawing, try to snap to a grid. If you match your
  # paper, then lines will be on the same grid as the paper.
  grid-snap: 5

  # Used for page "title" attributes
  top-margin: 10
  title-font:
    family: Helvetica
    size: 16
  title-color: "#666"
  title-align: Center

  # Used for section titles
  section-top-margin: 5
  section-title-font:
    family: Helvetica
    size: 10
  section-title-color: "#666"
  section-date-format: "%-d %b" # see datetime.strftime docs for formats
  section-left-margin: 15

  # Defaults for drawing lines
  line-color: "#ccc"
  line-width: 0.2

  # Used for the footer
  footer: "$page$" # To get the page number
  footer-font:
    family: Helvetica
    size: 8
  footer-color: "#666"
  footer-align: Center
  footer-offset: 5 # From the bottom

pages:
# Possible page types: simple, horizontal-sections
- type: simple
  title: 2023 Recurring Journal
  footer: Generated by Page-o-Mat

- type: simple
  title: 2023 Plan

- type: simple
  title: 2023 Retro

- count: 4 # Will repeat this page block 4 times. This is c[0] in day-of-year later.
  pages: # You can have sub-pages
  - type: horizontal-sections
    section-count: 13 # Will set s for day-of-year as it iterates
    section-top-margin: 0
    title: "Daily Summaries - $variant$" # $variant$ is set to the current variant
    section-title: "$section-start-date$"

    # Day of year can be an expression. It is calculated in the loop
    # that is generating pages for this page block.
    #
    # All indices are 0-based
    # - p is the current page
    # - c is a list of "count" indices (0 is the top level parent)
    # - s is a section index
    # - v is a variant index
    section-start-day-of-year: "2 + 7 * c[0] + 28 * s + v"

    # Will make this section repeat for each variant, setting $variant$ to the string
    # for use in the title and v to the index for use in day-of-year.
    variants:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday

- type: simple
  title: "$date$"
  day-of-year: 1 # January 1st
  date-format: "%A - %-d %b"

- type: simple

- type: horizontal-sections
  section-count: 2 # Will set s as it iterates
  section-title: "13 Week Plan: $section-start-date$ - $section-end-date$"
  section-start-day-of-year: "2 + c[0] * (13*7*2) + s * (13*7)"
  section-end-day-of-year: "2 + c[0] * (13*7*2) + s * (13*7) + (13*7-1)"
  count: 2 # Will set c[0] as it iterates

- count: 2
  pages:
  - type: horizontal-sections
    section-count: 2
    section-title: "4 Week Plan: $section-start-date$ - $section-end-date$"
    section-start-day-of-year: "2 + c[0] * 28 + c[1] * (13*7*2) + s * (13*7)"
    section-end-day-of-year: "2 + c[0] * 28 + c[1] * (13*7*2) + s * (13*7) + (4*7-1)"
    count: 2

  - count: 4
    pages:
    - type: horizontal-sections
      section-count: 2
      section-title: "1 Week Plan: $section-start-date$ - $section-end-date$"
      section-start-day-of-year: "2 + c[0] * 28 + c[1] * 7 + c[2] * (13*7*2) + s * (13*7)"
      section-end-day-of-year: "2 + c[0] * 28 + c[1] * 7 + c[2] * (13*7*2) + s * (13*7) + (7-1)"
      count: 2

    - type: horizontal-sections
      section-count: 2
      count: 2
      section-title: "$section-start-date$"
      section-date-format: "%A - %-d %b"
      section-start-day-of-year: "2 + 28 * c[0] + 7 * c[1] + 182 * c[2] + 91 * s + v"
      variants:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday

    - type: horizontal-sections
      section-count: 2
      section-title: "1 Week Retro: $section-start-date$ - $section-end-date$"
      section-start-day-of-year: "2 + c[0] * 28 + c[1] * 7 + c[2] * (13*7*2) + s * (13*7)"
      section-end-day-of-year: "2 + c[0] * 28 + c[1] * 7 + c[2] * (13*7*2) + s * (13*7) + (7-1)"
      count: 2

    - type: simple
      count: 2

  - type: horizontal-sections
    section-count: 2
    section-title: "4 Week Retro: $section-start-date$ - $section-end-date$"
    section-start-day-of-year: "2 + c[0] * 28 + c[1] * (13*7*2) + s * (13*7)"
    section-end-day-of-year: "2 + c[0] * 28 + c[1] * (13*7*2) + s * (13*7) + (4*7-1)"
    count: 2

  - type: simple
    count: 2

- type: horizontal-sections
  section-count: 2
  section-title: "5 Week Plan: $section-start-date$ - $section-end-date$"
  section-start-day-of-year: "(2+8*7) + c[0] * (13*7*2) + s * (13*7)"
  section-end-day-of-year: "(2+8*7) + c[0] * (13*7*2) + s * (13*7) + (5*7-1)"
  count: 2

- count: 5 # Sets c[0]
  pages:
  - type: horizontal-sections
    section-count: 2 # Sets s
    section-title: "1 Week Plan: $section-start-date$ - $section-end-date$"
    section-start-day-of-year: "(2+8*7) + c[0] * 7 + c[1] * (13*7*2) + s * (13*7)"
    section-end-day-of-year: "(2+8*7) + c[0] * 7 + c[1] * (13*7*2) + s * (13*7) + (7-1)"
    count: 2 # Sets c[1]

  - type: horizontal-sections
    section-count: 2 # Sets s
    count: 2 # Sets c[1]
    section-title: "$section-start-date$"
    section-date-format: "%A - %-d %b"
    section-start-day-of-year: "(2+8*7) + 7 * c[0] + 182 * c[1] + 91 * s + v"
    variants: # Sets v to the index
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    - Sunday

  - type: horizontal-sections
    section-count: 2
    section-title: "1 Week Retro: $section-start-date$ - $section-end-date$"
    section-start-day-of-year: "(2+8*7) + c[0] * 7 + c[1] * (13*7*2) + s * (13*7)"
    section-end-day-of-year: "(2+8*7) + c[0] * 7 + c[1] * (13*7*2) + s * (13*7) + (7-1)"
    count: 2

  - type: simple
    count: 2

- type: horizontal-sections
  section-count: 2
  section-title: "5 Week Retro: $section-start-date$ - $section-end-date$"
  section-start-day-of-year: "(2+8*7) + c[0] * (13*7*2) + s * (13*7)"
  section-end-day-of-year: "(2+8*7) + c[0] * (13*7*2) + s * (13*7) + (5*7-1)"
  count: 2

- type: horizontal-sections
  section-count: 2
  section-title: "13 Week Retro: $section-start-date$ - $section-end-date$"
  section-start-day-of-year: "2 + c[0] * (13*7*2) + s * (13*7)"
  section-end-day-of-year: "2 + c[0] * (13*7*2) + s * (13*7) + (13*7-1)"
  count: 2

- type: simple
  count: 10

- type: simple
