---
# page-size can be one of A5, A4, A3, Letter or Legal
# If you choose A5, A4, A3, then all metrics are in mm
# If you choose Letter or Legal, then all metrics are in inches
page-size: A5

# For the PDF meta-data
pdf-title: 2025 Journal
pdf-author: Lou Franco

# The defaults are used on each page that doesn't override them
defaults:

  # Default year for the journal (can override at page level)
  year: 2025

  # To format dates in titles
  date-format: "%-d %b"

  # The base design of the paper
  paper:
    # type can be blank, dot, lined, or grid.
    type: dot
    # Used to draw the dot, which is a filled ellipse
    # Grid would use the same variables for lines
    spacing: 5
    dot-size: 0.5
    color: "#aaa"

  # Used for page "title" attributes
  top-margin: 10
  title-font:
    family: Helvetica
    size: 16
  title-color: "#666"
  title-align: Center

  # Used for section titles
  section-title-font:
    family: Helvetica
    size: 10
  section-title-color: "#666"
  section-date-format: "%-d %b" # see datetime.strftime docs for formats
  section-left-margin: 15

  footer: "$page$" # To get the page number
  footer-font:
    family: Helvetica
    size: 8
  footer-color: "#666"
  footer-align: Center
  footer-offset: 5 # From the bottom

  # Defaults for drawing lines
  line-color: "#ccc"
  line-width: 0.2

pages:
# Possible page types: simple, horizontal-sections
- type: simple
  title: 2025 Journal
  footer: Generated by Page-o-Mat

- type: simple
  title: 2025 Plan

- type: simple
  title: 2025 Retro

- count: 4
  pages:
  - type: horizontal-sections
    title: Plan for 13 Weeks
    section-count: 13
    section-start-year: "2024 if c[0] == 0 and s == 0 else 2025"
    section-end-year: 2025
    section-start-day-of-year: "365+s if c[0] == 0 and s == 0 else (c[0]*13*7)+(s-1)*7 + 6"
    section-end-day-of-year: "(c[0]*13*7)+s*7 + 5"
    section-date-format: "%-d %b"
    section-title: "$section-start-date$ - $section-end-date$"
    section-page-link: "(p+1)+(s*9)+1"
    grid-snap: 5
    section-top-margin: -2

  - count: 13
    pages:
      - type: simple
        title: "Plan for $start-date$ - $end-date$"
        start-year: "2024 if c[0]==0 and c[1]==0 and c[2] < 2 else 2025"
        start-day-of-year: "365 if c[0]==0 and c[1]==0 else (c[0]*13*7)+(c[1]-1)*7+6"
        end-year: 2025
        end-day-of-year: "(c[0]*13*7)+c[1]*7+5"
        page-link: "(p+1)+8"

      - type: horizontal-sections
        count: 7
        section-count: 2
        section-title: ["", "Food Log"]
        section-top-margin: 7
        date-format: "%A - %-d %b"
        title: "$date$"
        year: "2024 if c[0]==0 and c[1]==0 and c[2] < 2 else 2025"
        day-of-year: "365+c[2] if c[0]==0 and c[1]==0 and c[2] < 2 else (c[0]*13*7)+c[1]*7+c[2]-1"

      - type: simple
        title: "Retro for $start-date$ - $end-date$"
        start-year: "2024 if c[0]==0 and c[1]==0 and c[2] < 2 else 2025"
        start-day-of-year: "365 if c[0]==0 and c[1]==0 else (c[0]*13*7)+(c[1]-1)*7+6"
        end-year: 2025
        end-day-of-year: "(c[0]*13*7)+c[1]*7+5"
        page-link: "(p+1)-8"

  - type: horizontal-sections
    title: Retro for 13 Weeks
    section-count: 13
    section-start-year: "2024 if c[0] == 0 and s == 0 else 2025"
    section-end-year: 2025
    section-start-day-of-year: "365+s if c[0] == 0 and s == 0 else (c[0]*13*7)+(s-1)*7 + 6"
    section-end-day-of-year: "(c[0]*13*7)+s*7 + 5"
    section-date-format: "%-d %b"
    section-title: "$section-start-date$ - $section-end-date$"
    section-page-link: "(p+1)-((13-s)*9)"
    grid-snap: 5
    section-top-margin: -2

# last week of the year

- type: simple
  title: "Plan for $start-date$ - $end-date$"
  start-year: 2025
  start-day-of-year: 363
  end-year: 2026
  end-day-of-year: 4
  page-link: "(p+1)+8"

- type: horizontal-sections
  section-count: 2
  section-title: ["", "Food Log"]
  section-top-margin: 7
  count: 7
  date-format: "%A - %-d %b"
  title: "$date$"
  year: "2025 if c[0]<3 else 2026"
  day-of-year: "363+c[0] if c[0] < 3 else c[0]-2"

- type: simple
  title: "Retro for $start-date$ - $end-date$"
  start-year: 2025
  start-day-of-year: 363
  end-year: 2026
  end-day-of-year: 4
  page-link: "(p+1)-8"